### ISSUE TITLE
Missing Mythic Passive Data , Attack Speed Treatment

### ISSUE THREAD

**Issue by egreen18** [meraki-analytics/lolstaticdata#31]
Good afternoon,

I noticed that the following items do not have any stats for their mythic passives:

                Shurelya's Battlesong, ID: 2065
                Locket of the Iron Solari, ID: 3190
                Stridebreaker, ID: 6631
                Frostfire Gauntlet, ID: 6662
                Turbo Chemtank, ID: 6664
                Galeforce, ID: 6671
                Immortal Shieldbow, ID: 6673
                Turbocharged Hexperiment, ID: 7003
                Rimeforged Grasp, ID: 7005
                Typhoon, ID: 7006
                Bloodward, ID: 7008
                Dreamshatter, ID: 7016
                Reliquary of the Golden Dawn, ID: 7019
                Shurelya's Requiem, ID: 7020

I expected all items to follow the format set forth by Kraken Slayer, ID 6672, where the stat gained per legendary item by the mythic passive is included in (item).passives(mythic).stats.(relevant stat) . As a side note, I would like to point out that attack speed is treated variably across items and champions. Sometimes it appears in the "flat" field, and sometimes it appears in the "percent" field. It is my understanding from my personal testing within the league client that attack speed bonuses from all items and levels gained by champions in fact functions as "percentBase". Please do correct me if I am wrong. 

Best,

Ethan

**Comment by jjmaldonis** [comment]
Thanks for the careful identification of what needs to be updated! I'm sure that took some time. Would you be willing to make a PR to fix these issues? I'm not sure why the passives in mythic items aren't being parsed, but it's probably just that we need to update our regexes. @dryancd may want to take a stab at it too (he's the primary maintainer of this code) but I don't know how busy he is right now.

I'm 90% sure all attack speeds should be flat, which indicates that they are additive quantities not multiplicative. Some items may function differently, but I'm not sure. For now, skip this. It's a separate issue that we can address in a different commit if we need to. Need more information first.

**Comment by egreen18** [comment]
Hello!

I am rather new to participating in the GitHub community and don't actually know how to complete a Pull Request or what that entails... I looked into it last time I submitted an issue on this repository and couldn't wrap my head around everything. I am not actually familiar with Python, I am using MATLAB to parse through the data that you all have created using your script. Does making a PR require me to have some understanding of Python and how to fix the root issue that is causing the results I am seeing in the JSON files? Are there any resources you could point me towards to help develop myself into a more resourceful contributor?

Best,

Ethan

**Comment by jjmaldonis** [comment]
No worries it's a complicated process because a lot of the working details are "hidden" from you as a user.

If you don't know `git` and if you aren't familiar with the command line then I wouldn't worry about it. If you are or if you want to learn, the commands `git pull origin <branch>`, `git clone <github url>`, `git add -u .`, and `git push origin <branch>` are important to know. There are lots of tutorials on them. The other important thing to know that tutorials don't tell you is that in order to create a PR you need to 1) fork a repo, 2) `git clone` that repo to your computer, 3) make and commit changes, 4) push those changes to your forked repo. At that point github will show a button that says "create pull request", which says "tell the owners of the forked library that I want to update their repo to look like my repo". At that point, all the differences between your updated forked repo and the original repo will be included the pull request.

Making the PR probably does require you to have some understanding of Python, which might be another big hurdle.

**Comment by dryancd** [comment]
I’ll fix it today

**Comment by Galvantua** [comment]
What is the status on this? It appears that these items have their stats as expected.

**Comment by rdavis0** [comment]
@Galvantua Agreed. All of these look to be correct now, though Heartsteel is missing its mythic bonus. I'm adding a new issue for that case since these appear to all be fixed.

**Comment by jjmaldonis** [comment]
Great, thank you both for looking into this.
